#ifndef G_CODES_H
#define G_CODES_H

#include <string>
#include <map>

namespace NCParser {

enum GCodesAvailable {
    rapid_positioning,
    linear_interpolation,
    circular_interpolation_cw,
    circular_interpolation_ccw,
    dwell,
    parabolic_interpolation,
    exact_stop,
    exact_stop_block,
    xy_plane_selection,
    zx_plane_selection,
    zy_plane_selection,
    thread_cutting_constant_lead,
    thread_cutting_increasing_lead,
    thread_cutting_decreasing_lead,
    cutter_compensation_cancel,
    cutter_compensation_left,
    cutter_compensation_right,
    tool_offset_positive,
    tool_offset_negative,
    dimension_shift_cancel,
    zero_shift,
    tapping,
    continuous_path_mode,
    dimension_input_inch,
    dimension_input_metric,
    home_position,
    fixed_cycle_cancel,
    fixed_cycle,
    absolute_dimension,
    incremental_dimension,
    preload_registers,
    inverse_time,
    feed_per_minute,
    feed_per_revolution,
    constant_surface_speed,
    revolutions_per_minute,
    coordinate_system_set,
    initial_level_return_fixed,
    r_point_return_fixed,
    rpm_limit,
    feed_correction,
    feed_correction_off,
    home_position_x,
    home_position_y,
    home_position_z,
    home_position_ordered_xz,
    home_position_ordered_zx,
    rapid_direct_to_reference,
    rapid_relative_to_reference,
    linear_interpolation_with_feed_reduction,
    cutter_compensation_auto,
    lin_interpol_with_collision_stop,
    cutting_cycle_convex_tool_x,
    cutting_cycle_concave_tool_x,
    cutting_cycle_z,
    cutting_cycle_same_contour,
    cutting_cycle_straight_with_fallback,
    cutting_cycle_straight_with_fallback_z,
    bevel_cycle_towards_spindle,
    bevel_cycle_against_spindle,
    cycle_repetition,
    drill_cycle_step_number,
    drill_cycle_step_distance,
    thread_cutting_variable_lead,
    thread_cutting_cycle,
    load_subprogram,
    auto_geometry_function,
};

struct GCodeDescription {
    std::string name;
    std::string description;
};

static const std::map<int,GCodeDescription> gcode_descriptions = {
    {rapid_positioning, {"Rapid positioning"}},
    {linear_interpolation, {"Linear interpolation"}},
    {circular_interpolation_cw, {"Circular interpolation arc clockwise"}},
    {circular_interpolation_ccw, {"Circular interpolation arc counter-clockwise"}},
    {dwell, {"Dwell"}},
    {parabolic_interpolation, {"Parabolic interpolation"}},
    {exact_stop, {"Exact stop"}},
    {exact_stop_block, {}},
    {xy_plane_selection, {"XY plane selection"}},
    {zx_plane_selection, {"ZX plane selection"}},
    {zy_plane_selection, {"ZY plane selection"}},
    {thread_cutting_constant_lead, {"Thread cutting, constant lead"}},
    {thread_cutting_increasing_lead, {"Thread cutting, increasing lead"}},
    {thread_cutting_decreasing_lead, {"Thread cutting, decreasing lead"}},
    {cutter_compensation_cancel, {"Cutter compensation cancel"}},
    {cutter_compensation_left, {"Cutter compensation left"}},
    {cutter_compensation_right, {"Cutter compensation right"}},
    {tool_offset_positive, {"Tool offset positive"}},
    {tool_offset_negative, {"Tool offset negative"}},
    {dimension_shift_cancel, {"Dimension shift cancel"}},
    {zero_shift, {"Zero shift"}},
    {tapping, {"Tapping"}},
    {continuous_path_mode, {"Continuous-path mode"}},
    {dimension_input_inch, {"Dimension input inch"}},
    {dimension_input_metric, {"Dimension input metric"}},
    {home_position, {"Home position"}},
    {fixed_cycle_cancel, {"Fixed cycle cancel"}},
    {fixed_cycle, {"Fixed cycle"}},
    {absolute_dimension, {"Absolute dimension"}},
    {incremental_dimension, {"Incremental dimension"}},
    {preload_registers, {"Preload registers"}},
    {inverse_time, {"Inverse time"}},
    {feed_per_minute, {"Feed per minute"}},
    {feed_per_revolution, {"Feed per revolution"}},
    {constant_surface_speed, {"Constant surface speed"}},
    {revolutions_per_minute, {"Revolutions per minute"}},
    {coordinate_system_set, {}},
    {initial_level_return_fixed, {}},
    {r_point_return_fixed, {}},
    {rpm_limit, {"Revolutions per minute limit"}},
    {feed_correction, {}},
    {feed_correction_off, {}},
    {home_position_x, {"Home position on the X axis"}},
    {home_position_y, {"Home position on the Y axis"}},
    {home_position_z, {"Home position on the Z axis"}},
    {home_position_ordered_xz, {"Home position on first X then Z axis'"}},
    {home_position_ordered_zx, {"Home position on first Z then X axis'"}},
    {rapid_direct_to_reference, {"Home to reference point"}},
    {rapid_relative_to_reference, {"Rapid positioning relative to reference point"}},
    {linear_interpolation_with_feed_reduction, {}},
    {cutter_compensation_auto, {}},
    {lin_interpol_with_collision_stop, {}},
    {cutting_cycle_convex_tool_x, {}},
    {cutting_cycle_concave_tool_x, {}},
    {cutting_cycle_z, {}},
    {cutting_cycle_same_contour, {}},
    {cutting_cycle_straight_with_fallback, {}},
    {cutting_cycle_straight_with_fallback_z, {}},
    {bevel_cycle_towards_spindle, {}},
    {bevel_cycle_against_spindle, {}},
    {cycle_repetition, {}},
    {drill_cycle_step_number, {}},
    {drill_cycle_step_distance, {}},
    {thread_cutting_variable_lead, {}},
    {thread_cutting_cycle, {}},
    {load_subprogram, {}},
};

};

#endif // G_CODES_H
