#ifndef G_CODES_H
#define G_CODES_H

namespace NCParser {

enum GCodesAvailable {
    // Marks G-codes that need to call a translation function
    g_auto_geometry_function,

    // Normal G-codes
    g_absolute_dimension,
    g_use_subsystem_a,
    g_use_subsystem_b,
    g_use_subsystem_c,
    g_use_subsystem_d,
    g_bevel_cycle_against_spindle,
    g_bevel_cycle_towards_spindle,
    g_chuck_transfer_under_torque,
    g_circular_interpolation_ccw,
    g_circular_interpolation_cw,
    g_circular_interpolation_ccw_milling_on_turning,
    g_circular_interpolation_cw_milling_on_turning,
    g_constant_surface_speed,
    g_continuous_path_mode,
    g_coordinate_system_set,
    g_coordinate_cartesian_to_polar,
    g_coordinate_cartesian_to_polar_off,
    g_cutter_compensation_auto,
    g_cutter_compensation_cancel,
    g_cutter_compensation_left,
    g_cutter_compensation_right,
    g_cutting_cycle_concave_tool_x,
    g_cutting_cycle_convex_tool_x,
    g_cutting_cycle_same_contour,
    g_cutting_cycle_straight_with_fallback,
    g_cutting_cycle_straight_with_fallback_z,
    g_cutting_cycle_z,
    g_cycle_repetition,
    g_dimension_input_inch,
    g_dimension_input_metric,
    g_dimension_shift_cancel,
    g_drill_cycle_step_distance,
    g_drill_cycle_step_number,
    g_drill_cycle_z_axis,
    g_dwell,
    g_exact_stop,
    g_exact_stop_block,
    g_feed_correction,
    g_feed_correction_off,
    g_feed_per_minute,
    g_feed_per_revolution,
    g_fixed_cycle,
    g_fixed_cycle_cancel,
    g_home_position,
    g_home_position_ordered_xz,
    g_home_position_ordered_zx,
    g_home_position_x,
    g_home_position_y,
    g_home_position_z,
    g_incremental_dimension,
    g_initial_level_return_fixed,
    g_inverse_time,
    g_linear_interpolation,
    g_linear_interpolation_with_collision_stop,
    g_linear_interpolation_with_feed_reduction,
    g_load_subprogram,
    g_milling_interpolation_off,
    g_milling_interpolation_on,
    g_milling_line_end_face,
    g_milling_curve_cw_end_face,
    g_milling_curve_ccw_end_face,
    g_milling_tool_compensation_cancel,
    g_milling_tool_compensation_left,
    g_milling_tool_compensation_right,
    g_parabolic_interpolation,
    g_preload_registers,
    g_r_point_return_fixed,
    g_rapid_direct_to_reference,
    g_rapid_positioning,
    g_rapid_relative_to_reference,
    g_revolutions_per_minute,
    g_rpm_limit,
    g_servo_error_compensation_off,
    g_servo_error_compensation_on,
    g_tapping,
    g_thread_cutting_circular_ccw,
    g_thread_cutting_circular_cw,
    g_thread_cutting_constant_lead,
    g_thread_cutting_cycle,
    g_thread_cutting_cycle_end_face,
    g_thread_cutting_decreasing_lead,
    g_thread_cutting_end_face,
    g_thread_cutting_increasing_lead,
    g_thread_cutting_multistep,
    g_thread_cutting_variable_lead,
    g_tool_offset_negative,
    g_tool_offset_positive,
    g_torque_limit_chuck_transfer,
    g_torque_limit_chuck_transfer_off,
    g_transfer_chamfer,
    g_transfer_radius,
    g_wedge_cut_cycle_lengthwise,
    g_xy_plane_selection,
    g_xz_cylindrical_plane_selection,
    g_yz_cylindrical_plane_selection,
    g_yz_plane_selection,
    g_zero_set,
    g_zero_shift,
    g_zx_plane_selection,
    g_zy_plane_selection,
    g_turning_mode,
    g_c_axis_mode,
    g_y_axis_mode,
};

};

#endif // G_CODES_H
