#ifndef M_CODES_H
#define M_CODES_H

namespace NCParser {

enum MCodesAvailable {
    m_activate_c_axis,
    m_activate_c_axis_opposing_spindle,
    m_alarm_on_stm_time_passed_off,
    m_alarm_on_stm_time_passed_on,
    m_bypass_override,
    m_bypass_override_off,
    m_c_axis_lock,
    m_c_axis_rotation_left,
    m_c_axis_rotation_right,
    m_c_axis_unlock,
    m_c_axis_use_locking,
    m_chuck_barrier_off,
    m_chuck_barrier_on,
    m_chuck_opening_allowed_on_spindle_rotation_off,
    m_chuck_opening_allowed_on_spindle_rotation_on,
    m_clamp_workpiece,
    m_deactivate_c_axis,
    m_deactivate_c_axis_opposing_spindle,
    m_double_dock_barrier_off,
    m_double_dock_barrier_on,
    m_end_of_data,
    m_end_of_program,
    m_feed_limit_manual_obey_off,
    m_feed_limit_manual_obey_on,
    m_feed_rate_nowait,
    m_feed_rate_wait,
    m_multiop_rpm_max,
    m_multiop_rpm_min,
    m_nub_allowed_on_spindle_rotation_off,
    m_nub_allowed_on_spindle_rotation_on,
    m_nub_workmode_off,
    m_nub_workmode_on,
    m_nubdock,
    m_nubdock_retract,
    m_optional_stop,
    m_profile_for_fixed_cycle,
    m_program_stop,
    m_queueing,
    m_revolver_allowed_without_axis_c_off,
    m_revolver_allowed_without_axis_c_on,
    m_revolver_cw_locked,
    m_revolver_cw_unlocked,
    m_rpm_limit_manual_obey_off,
    m_rpm_limit_manual_obey_on,
    m_scrub_cycle_noreturn,
    m_single_block_obey_off,
    m_single_block_obey_on,
    m_spindle_ccw,
    m_spindle_cw,
    m_spindle_gear_1,
    m_spindle_gear_2,
    m_spindle_gear_3,
    m_spindle_gear_4,
    m_spindle_gear_neutral,
    m_spindle_off,
    m_spindle_on_axis_c_off,
    m_spindle_on_axis_c_on,
    m_spindle_rotation_nowait,
    m_thread_chamfer_off,
    m_thread_chamfer_on,
    m_thread_cut_straight_left,
    m_thread_cut_straight_right,
    m_thread_cut_zigzag,
    m_thread_cycle_schema_1,
    m_thread_cycle_schema_2,
    m_thread_cycle_schema_3,
    m_thread_pitch_axis_x,
    m_thread_pitch_axis_z,
    m_thread_tool_rpm_nowait,
    m_tool_change,
    m_unclamp_workpiece,
    m_wedge_track_cycle_equal_cutting_amount,
    m_wedge_track_cycle_single_dimension,
    m_wedge_track_cycle_single_zigzag,
    m_wedge_track_cycle_specific_cutting_amount,
    m_workpiece_change,

    //m_thread_cycle_phase_compensation_on,
    //m_thread_cycle_phase_compensation_off,
    //m_thread_cycle_save_manual_phase_compensation
};

};

#endif // M_CODES_H
